### ISSUE TITLE
Social drone project

### ISSUE THREAD

**Issue by oqvd96** [zeruniverse/Gesture_Recognition#1]
Dear,

I am Olivier van Duuren from the Netherlands and I am running a project at studentteam Blue Jay Eindhoven (www.bluejayeindhoven.nl). I am interested to add rock, paper, scissor to it, but need some help to achieve it. Are you able and interested to help me with this project? If yes, please contact me via olivier@bluejayeindhoven.nl and I will provide you of more information. Hope to see a reply from you soon!  Thank you in advance!

Kind regards,

Olivier

**Comment by zeruniverse** [comment]
Hello Olivier,

Thank you for your interest in this project! I'm willing to help if it
won't take me much time. But please don't put too much hope. It's a project
I did 2 years ago and I'm afraid I can't remember details.

Sincerely,
Jeffery.
