### ISSUE TITLE
Scissor Recognition

### ISSUE THREAD

**Issue by hassanyawar** [zeruniverse/Gesture_Recognition#4]
Good work on the project. How ever on testing scissor gesture I checked that I can make it recognize scissor by using any two fingers rather than specifically index finger and middle finger. Shouldn't it be restricted to index and middle finger?

**Comment by zeruniverse** [comment]
Yes. But how do you figure out which finger it is? It’s pretty difficult

**Comment by hassanyawar** [comment]
It is indeed difficult. So far my research on this goes you may need to add a classifier and train it using a dataset. But there is a possibility there the responsiveness of the application may take a hit. As constantly using a classifier does adds its overhead. I myself am finding the recognition process difficult. Thought I might ask.

**Comment by zeruniverse** [comment]
I don't plan to implement this. It's a project I did long time ago and I don't even remember every detail.

In addition, I think geometric way to figure out certain fingers is hopeless. You need machine learning. I think there're not many datasets containing 'scissor' images. If you are willing to label around 1000 images for rock sscissor and paper, you can do this recognition (actually detection) with [faster-RCNN](https://arxiv.org/abs/1506.01497).

**Comment by zeruniverse** [comment]
closed due to inactivity
